### ISSUE TITLE
Bug: casting 'False' to boolean returns True

### ISSUE THREAD

**Issue by rdonnelly3** [datafuselabs/databend-py#77]
`result = db_conn.execute("select 'False'::boolean union select 'True'::boolean")

print(result)`

This returns:

`([], [(True,), (True,)])`

Running the same query outside of Python returns the correct results False, True

**Comment by hantmac** [comment]
@rdonnelly3 Thanks for your report! Maybe it's a bug, I will check and fix it.

**Comment by hantmac** [comment]
@rdonnelly3 Bug has been fixed. Thanks!
